### ISSUE TITLE
Don't create comment if nothing has changed

### ISSUE THREAD

**Issue by maxnowack** [DevCycleHQ/feature-flag-pr-insights-action#24]
It would be great if there was a way to not comment on the pull request if there were no changes.
This will reduce noise in the pull request conversation.
We use a few bots that leave comments on the pull requests and it gets messy quickly. Therefore, we try to avoid comments from bots if they are not necessary.

**Comment by laurawarr** [comment]
Hey @maxnowack, thanks for this feedback. I took your PR into consideration and added an optional parameter `only-comment-on-change` to only add a PR comment if DevCycle variable changes are detected
https://github.com/marketplace/actions/devcycle-feature-flag-insights-for-pull-requests#inputs
